### ISSUE TITLE
Can't find the part of the code where the binary encoding is decoded

### ISSUE THREAD

**Issue by Afterg10w** [Madaoer/Neural-Field-Classifier#2]
I can't find the part of the code related to binary encoding decoding when trying to add nfc to other frameworks. Can you please help point out where this part of the code is?

**Comment by Madaoer** [comment]
Sure! You can find the relevant code [here](https://github.com/Madaoer/Neural-Field-Classifier/blob/main/models/DVGO/lib/dcvgo_bce.py#L354).

**Comment by Afterg10w** [comment]
I still don't understand how the code represents the color value y as an 8-bit binary number y，As mentioned in the paper
y = BinaryEncod(203)= [1, 1, 0, 0, 1, 0, 1, 1]

**Comment by Madaoer** [comment]
This is a binary encoding method. For example, the decimal number 4 can be represented in binary as [1, 0, 0] ($2^2 \times 1 + 2^1 \times 0 + 2^0 \times 0$).
So, for the decimal number 203, we can get it binary number as [1, 1, 0, 0, 1, 0, 1, 1]
$203 = 2^7 \times 1 + 2^6 \times 1 + 2^5 \times 0 + 2^4 \times 0 + 2^3 \times 1 + 2^2 \times 0 + 2^1 \times 1 + 2^0 \times 1$

**Comment by Afterg10w** [comment]
oh! I get it I didn't understand that weight before
